# Generated by Django 3.1.7 on 2021-05-04 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('no_ktp', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
                ('ask_1', models.CharField(choices=[('belum', 'BELUM'), ('sudah', 'SUDAH')], default='tidak', max_length=10)),
                ('ask_2', models.CharField(choices=[('belum', 'BELUM'), ('sudah', 'SUDAH')], default='tidak', max_length=10)),
                ('ask_3', models.CharField(choices=[('ya', 'YA'), ('tidak', 'TIDAK')], default='belum', max_length=10)),
                ('ask_4', models.CharField(choices=[('ya', 'YA'), ('tidak', 'TIDAK')], default='belum', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=12, null=True)),
                ('ask_1', models.CharField(blank=True, choices=[('belum', 'BELUM'), ('sudah', 'SUDAH')], default='tidak', max_length=10, null=True)),
                ('ask_2', models.CharField(blank=True, choices=[('belum', 'BELUM'), ('sudah', 'SUDAH')], default='tidak', max_length=10, null=True)),
                ('ask_3', models.CharField(blank=True, choices=[('ya', 'YA'), ('tidak', 'TIDAK')], default='belum', max_length=10, null=True)),
                ('ask_4', models.CharField(blank=True, choices=[('ya', 'YA'), ('tidak', 'TIDAK')], default='belum', max_length=10, null=True)),
                ('nik_emp', models.CharField(blank=True, max_length=12, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='ask.profile')),
            ],
        ),
    ]
