# Generated by Django 3.1.7 on 2021-05-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='ask_1',
            field=models.CharField(choices=[('belum', 'BELUM'), ('sudah', 'SUDAH')], default='tidak', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='ask_2',
            field=models.CharField(choices=[('belum', 'BELUM'), ('sudah', 'SUDAH')], default='tidak', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='ask_3',
            field=models.CharField(choices=[('ya', 'YA'), ('tidak', 'TIDAK')], default='belum', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='ask_4',
            field=models.CharField(choices=[('ya', 'YA'), ('tidak', 'TIDAK')], default='belum', max_length=10),
        ),
    ]
