# Generated by Django 3.1.7 on 2021-05-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20210505_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('suami', 'SUAMI'), ('istri', 'ISTRI'), ('anak', 'ANAK')], default='suami', max_length=100),
        ),
    ]
