# Generated by Django 3.1.7 on 2021-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20210505_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
