# Generated by Django 3.1.5 on 2021-01-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('latoffice', models.FloatField(max_length=14)),
                ('longoffice', models.FloatField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=6)),
                ('date', models.DateField(max_length=12)),
                ('time', models.TimeField(max_length=12)),
                ('lat', models.FloatField(max_length=14)),
                ('long', models.FloatField(max_length=14)),
                ('type_absen', models.CharField(max_length=10)),
                ('alamat', models.CharField(max_length=100)),
                ('status_absen', models.CharField(max_length=12)),
                ('type_work', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=6)),
                ('lat', models.FloatField(max_length=14)),
                ('long', models.FloatField(max_length=14)),
                ('address', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordinatoffice')),
            ],
        ),
        
    ]
