# Generated by Django 3.1.5 on 2021-01-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210113_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatuser',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coordinatoffice'),
        ),
    ]
