# Generated by Django 3.1.5 on 2021-01-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210113_1606'),
    ]

    operations = [
        
    ]
