# Generated by Django 3.1.5 on 2021-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=6)),
                ('date', models.DateField(max_length=12)),
                ('time_in', models.TimeField(max_length=12)),
                ('time_out', models.TimeField(max_length=12)),
            ],
        ),
    ]
