# Generated by Django 3.1.5 on 2021-01-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_timeview_users'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='timeview',
            name='time_in',
            field=models.TimeField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='timeview',
            name='time_out',
            field=models.TimeField(blank=True, max_length=12, null=True),
        ),
    ]
