# Generated by Django 3.1.5 on 2021-01-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210115_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeview',
            name='type_work',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
