# Generated by Django 3.1.5 on 2021-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210201_1340'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='WorkTasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=6)),
                ('task', models.TextField()),
                ('isfinish', models.BooleanField()),
                ('create_task', models.TimeField(max_length=12)),
                ('date', models.DateField(max_length=12)),
            ],
        ),
    ]
