# Generated by Django 3.1.5 on 2021-02-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_employee_users_worktaslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatoffice',
            name='latoffice',
            field=models.FloatField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatoffice',
            name='longoffice',
            field=models.FloatField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatoffice',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
