# Generated by Django 3.1.5 on 2021-02-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210205_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatuser',
            name='office',
        ),
        migrations.AddField(
            model_name='coordinatuser',
            name='office1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.coordinatoffice'),
        ),
        migrations.AddField(
            model_name='coordinatuser',
            name='office2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.coordinatoffice'),
        ),
        migrations.AddField(
            model_name='coordinatuser',
            name='office3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.coordinatoffice'),
        ),
        migrations.AddField(
            model_name='coordinatuser',
            name='office4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.coordinatoffice'),
        ),
        migrations.AddField(
            model_name='coordinatuser',
            name='office5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.coordinatoffice'),
        ),
        migrations.AddField(
            model_name='coordinatuser',
            name='office6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.coordinatoffice'),
        ),
    ]
