# Generated by Django 3.1.5 on 2021-02-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminuser_ahcbrowsers_ahccountries_ahcdailyvisitorsstats_ahchits_ahckeywords_ahconlineusers_ahcrecen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurresult',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workingcalendar',
            options={'managed': True},
        ),
    ]
