# Generated by Django 3.1.5 on 2021-02-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_workingcalendarcreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatuser',
            name='office1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office1', to='api.coordinatoffice'),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='office2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office2', to='api.coordinatoffice'),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='office3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office3', to='api.coordinatoffice'),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='office4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office4', to='api.coordinatoffice'),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='office5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office5', to='api.coordinatoffice'),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='office6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office6', to='api.coordinatoffice'),
        ),
    ]
