# Generated by Django 3.1.5 on 2021-02-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210220_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveheader',
            options={'managed': True},
        ),
    ]
