# Generated by Django 3.1.5 on 2021-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210222_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='loss_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
