# Generated by Django 3.1.5 on 2021-02-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210222_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='acc_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='crt_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='plan_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='plan_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp1_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp2_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp3_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='term_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='upd_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
