# Generated by Django 3.1.5 on 2021-02-22 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210222_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 55, 35, 993030)),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 55, 35, 993030)),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date3',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 55, 35, 993030)),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp1_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 55, 35, 992029)),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp2_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 55, 35, 992029)),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp3_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 14, 55, 35, 993030)),
        ),
    ]
