# Generated by Django 3.1.5 on 2021-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210222_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date3',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='in_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='out_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='plan_in',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='plan_out',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp1_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp2_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp3_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
