# Generated by Django 3.1.5 on 2021-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210222_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='in_time',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='out_time',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='plan_in',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='plan_out',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
    ]
