# Generated by Django 3.1.5 on 2021-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210222_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='acc_step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date1',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date2',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date3',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_term',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='loss_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp1_dt',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp2_dt',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp3_dt',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00.000000', null=True),
        ),
    ]
