# Generated by Django 3.1.5 on 2021-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210222_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='act_date3',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp1_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp2_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaveheader',
            name='sendapp3_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
