# Generated by Django 3.1.5 on 2021-02-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210223_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='lat',
            field=models.FloatField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='long',
            field=models.FloatField(blank=True, max_length=14, null=True),
        ),
    ]
