# Generated by Django 3.1.7 on 2021-03-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_coordinatuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
