# Generated by Django 3.1.7 on 2021-03-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210302_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteremployee',
            options={'managed': True},
        ),
    ]
