# Generated by Django 3.1.7 on 2021-03-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210304_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteremployee',
            options={},
        ),
        migrations.AlterModelTable(
            name='masteremployee',
            table=None,
        ),
    ]
