# Generated by Django 3.1.7 on 2021-03-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210304_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteremployee',
            options={'managed': True},
        ),
       
        migrations.AlterModelTable(
            name='masteremployee',
            table='master_employee',
        ),
    ]
