# Generated by Django 3.1.7 on 2021-03-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210304_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeview',
            name='data_emp',
        ),
        migrations.RemoveField(
            model_name='worktasklist',
            name='data_emp',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='data_emp',
        ),
    ]
