# Generated by Django 3.1.7 on 2021-03-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210306_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterdivision',
            options={'managed': True},
        ),
        
    ]
