# Generated by Django 3.1.7 on 2021-03-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210308_1724'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='timeview',
            name='date',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
       
        migrations.AlterField(
            model_name='worktasklist',
            name='date',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
       
        migrations.AlterField(
            model_name='worktime',
            name='date',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
    ]
