# Generated by Django 3.1.7 on 2021-03-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210309_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatoffice',
            name='radius',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
        
    ]
