# Generated by Django 3.1.7 on 2021-03-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210311_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatoffice',
            name='radius',
            field=models.FloatField(blank=True, default=10.0, max_length=4, null=True),
        ),
       
    ]
