# Generated by Django 3.1.7 on 2021-04-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210326_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatuser',
            name='radius',
            field=models.FloatField(blank=True, default=50.0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatuser',
            name='radius2',
            field=models.FloatField(blank=True, default=50.0, max_length=4, null=True),
        ),
        
    ]
